spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/wxshop?useSSL=false&allowPublicKeyRetrieval=true

mybatis:
  mapper-locations:
    - classpath:db/mybatis/*.xml
server:
  port: 8081

shop:
  redis:
    host: localhost
    port: 6379