CREATE TABLE `ORDER`
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    TOTAL_PRICE     BIGINT, -- 单位 分
    SHOP_ID         BIGINT,
    ADDRESS         VARCHAR(1024),
    EXPRESS_COMPANY VARCHAR(16),
    EXPRESS_ID      VARCHAR(128),
    STATUS          VARCHAR(16),
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE ORDER_GOODS
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT,
    GOODS_ID BIGINT,
    NUMBER   BIGINT
);

INSERT INTO `ORDER` (ID, USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, SHOP_ID)
VALUES (1, 1, 1400, '火星', '顺丰', '运单1234567', 'delivered',1);

INSERT INTO ORDER_GOODS(GOODS_ID, ORDER_ID, NUMBER)
VALUES (1, 1, 5),
       (2, 1, 9);