# Spring boot application
spring:
  application:
    name: shop-order

  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  ## dubbo.application.name=${spring.application.name}



dubbo:
  scan:
    base-packages: com.greek.order.service # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
  protocol:
    name: dubbo # Dubbo Protocol
    port: -1   # Random port
  registry:  ## Dubbo Registry
    address: zookeeper://192.168.20.111:2181


shop:
  orderservice:
    version: 0.0.1

server:
  port: 8082
